import type { RallioLocalSignal } from "@/lib/content/types";

// Generated from rallio_global_taste_map_fixed.csv as review-safe creative
// source material. Rows are not verified business facts; generated posts still
// require operator approval before Buffer handoff.
export const rallioSourceSignals = [
  {
    id: "golden-bowl-pho-chinatown",
    spot_name: "Golden Bowl Pho",
    neighborhood: "Chinatown",
    street: "Spadina Ave",
    category: "pho shop",
    signature_order: "rare beef pho with extra thai basil",
    sensory_detail: "the ceiling fan squeaks in rhythm with the kitchen chopping",
    regular_quote: "the broth cures everything after a long shift",
    regular_name: "Sarah",
    regular_since_year: "2017",
    participation_prompt: "Which broth belongs on the map around here",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "dundas-dumpling-house-kensington-market",
    spot_name: "Dundas Dumpling House",
    neighborhood: "Kensington Market",
    street: "Dundas St W",
    category: "dumpling counter",
    signature_order: "pan fried pork and chive dumplings",
    sensory_detail: "jars of black vinegar line the window sill",
    regular_quote: "they pan fry them so the bottom gets a thick crust",
    regular_name: "Chloe",
    regular_since_year: "2021",
    participation_prompt: "What dipping sauce ratio is favorite",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "college-street-tapas-little-italy",
    spot_name: "College Street Tapas",
    neighborhood: "Little Italy",
    street: "College St",
    category: "tapas bar",
    signature_order: "garlic shrimp and warm bread",
    sensory_detail: "the smell of roasted garlic hits you at the door",
    regular_quote: "bread is always warm enough to melt the butter instantly",
    regular_name: "Julian",
    regular_since_year: "2016",
    participation_prompt: "What small plate is mandatory here",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "brooklyn-broth-williamsburg",
    spot_name: "Brooklyn Broth",
    neighborhood: "Williamsburg",
    street: "Bedford Ave",
    category: "ramen bar",
    signature_order: "spicy tonkotsu with a soft boiled egg",
    sensory_detail: "the wooden stools scrape loudly on the concrete floor",
    regular_quote: "the pork chashu melts before you even chew it",
    regular_name: "Mia",
    regular_since_year: "2020",
    participation_prompt: "What bowl is favorite for winter nights",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "queens-curry-stand-jackson-heights",
    spot_name: "Queens Curry Stand",
    neighborhood: "Jackson Heights",
    street: "73rd St",
    category: "curry house",
    signature_order: "chicken tikka masala with garlic naan",
    sensory_detail: "the rhythmic slapping of naan dough echoes from the back",
    regular_quote: "the spices wake you up but never overwhelm the dish",
    regular_name: "Priya",
    regular_since_year: "2016",
    participation_prompt: "What side dish completes this order",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "uptown-wine-room-upper-west-side",
    spot_name: "Uptown Wine Room",
    neighborhood: "Upper West Side",
    street: "Columbus Ave",
    category: "wine bar",
    signature_order: "chilled natural orange wine",
    sensory_detail: "condensation drips down the chilled bottles behind the bar",
    regular_quote: "staff knows exactly what to pour based on the weather",
    regular_name: "Eleanor",
    regular_since_year: "2019",
    participation_prompt: "What glass belongs on the table",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "panaderia-azul-roma-norte",
    spot_name: "Panaderia Azul",
    neighborhood: "Roma Norte",
    street: "Colima",
    category: "bakery",
    signature_order: "concha de vainilla",
    sensory_detail: "the smell of melted butter and sugar fills the street by dawn",
    regular_quote: "the topping crumbles perfectly into your morning coffee",
    regular_name: "Sofia",
    regular_since_year: "2017",
    participation_prompt: "What pastry starts the day right",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "cantina-tarde-centro-historico",
    spot_name: "Cantina Tarde",
    neighborhood: "Centro Historico",
    street: "Bolivar",
    category: "bistro",
    signature_order: "mole poblano with rice",
    sensory_detail: "the wooden chairs are polished smooth from decades of use",
    regular_quote: "a mole recipe that tastes like it took a week to make",
    regular_name: "Maria",
    regular_since_year: "2016",
    participation_prompt: "What dish carries the most history",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "churro-central-coyoacan",
    spot_name: "Churro Central",
    neighborhood: "Coyoacan",
    street: "Ignacio Allende",
    category: "dessert shop",
    signature_order: "plain churros with thick chocolate dip",
    sensory_detail: "the bubbling oil sounds like quiet rain",
    regular_quote: "crispy outside and soft inside with just enough sugar",
    regular_name: "Luis",
    regular_since_year: "2020",
    participation_prompt: "Which dessert stands the test of time",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "soho-slice-soho",
    spot_name: "Soho Slice",
    neighborhood: "Soho",
    street: "Wardour St",
    category: "slice shop",
    signature_order: "margherita with garlic oil",
    sensory_detail: "the neon sign buzzes slightly over the register",
    regular_quote: "great crust chew and they do not skimp on the basil",
    regular_name: "James",
    regular_since_year: "2019",
    participation_prompt: "What slice style wins here",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "brick-lane-brew-shoreditch",
    spot_name: "Brick Lane Brew",
    neighborhood: "Shoreditch",
    street: "Brick Ln",
    category: "coffee bar",
    signature_order: "cortado with a dash of cinnamon",
    sensory_detail: "the espresso machine hisses every two minutes",
    regular_quote: "the barista remembers your face after one visit",
    regular_name: "Emma",
    regular_since_year: "2020",
    participation_prompt: "Where do locals get their caffeine",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "camden-curry-camden",
    spot_name: "Camden Curry",
    neighborhood: "Camden",
    street: "Parkway",
    category: "curry house",
    signature_order: "lamb bhuna with pilau rice",
    sensory_detail: "the aroma of toasted cumin lingers on your jacket",
    regular_quote: "the lamb is so tender it falls apart with a fork",
    regular_name: "Aisha",
    regular_since_year: "2016",
    participation_prompt: "Which spice level is the favorite choice",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "mayfair-vintners-mayfair",
    spot_name: "Mayfair Vintners",
    neighborhood: "Mayfair",
    street: "Mount St",
    category: "wine bar",
    signature_order: "rioja reserva",
    sensory_detail: "the glasses are polished until they squeak",
    regular_quote: "a quiet place with pours that justify the visit",
    regular_name: "Henry",
    regular_since_year: "2018",
    participation_prompt: "What red wine fits a rainy evening",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "boulangerie-matin-le-marais",
    spot_name: "Boulangerie Matin",
    neighborhood: "Le Marais",
    street: "Rue des Rosiers",
    category: "bakery",
    signature_order: "croissant au beurre",
    sensory_detail: "the paper bag becomes transparent with butter instantly",
    regular_quote: "flaky layers that shatter when you tear it",
    regular_name: "Antoine",
    regular_since_year: "2017",
    participation_prompt: "Which morning pastry rules this street",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "cave-a-vin-bastille",
    spot_name: "Cave a Vin",
    neighborhood: "Bastille",
    street: "Rue de la Roquette",
    category: "wine bar",
    signature_order: "beaujolais nouveau",
    sensory_detail: "the chalk menu board is smudged from daily updates",
    regular_quote: "a relaxed atmosphere with truly great regional pours",
    regular_name: "Camille",
    regular_since_year: "2019",
    participation_prompt: "What glass starts the evening",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "crepe-de-nuit-latin-quarter",
    spot_name: "Crepe de Nuit",
    neighborhood: "Latin Quarter",
    street: "Rue Mouffetard",
    category: "dessert shop",
    signature_order: "crepe with salted caramel",
    sensory_detail: "the wooden spreader clacks against the hot iron griddle",
    regular_quote: "caramel that is the perfect balance of sweet and salty",
    regular_name: "Chloe",
    regular_since_year: "2020",
    participation_prompt: "What sweet order is required",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "kebab-royale-belleville",
    spot_name: "Kebab Royale",
    neighborhood: "Belleville",
    street: "Rue de Belleville",
    category: "kebab shop",
    signature_order: "lamb shawarma in fresh flatbread",
    sensory_detail: "the smell of sumac onions hits you from a block away",
    regular_quote: "they pack the meat tight so it stays warm",
    regular_name: "Omar",
    regular_since_year: "2018",
    participation_prompt: "Which late night food is essential",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "tasca-de-prata-alfama",
    spot_name: "Tasca de Prata",
    neighborhood: "Alfama",
    street: "Rua dos Remedios",
    category: "tapas bar",
    signature_order: "grilled sardines with boiled potatoes",
    sensory_detail: "coarse sea salt crunches lightly under your teeth",
    regular_quote: "the smokiness of the grill stays in the fish perfectly",
    regular_name: "Tiago",
    regular_since_year: "2016",
    participation_prompt: "Which grilled dish is local tradition",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "bifana-central-baixa",
    spot_name: "Bifana Central",
    neighborhood: "Baixa",
    street: "Rua da Madalena",
    category: "sandwich counter",
    signature_order: "traditional pork bifana with mustard",
    sensory_detail: "the pork stews in a huge metal pan visible from the street",
    regular_quote: "bread is soft enough to absorb all the garlic pan juices",
    regular_name: "Ines",
    regular_since_year: "2018",
    participation_prompt: "What sandwich defines this city",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "vinho-verde-spot-bairro-alto",
    spot_name: "Vinho Verde Spot",
    neighborhood: "Bairro Alto",
    street: "Rua da Rosa",
    category: "wine bar",
    signature_order: "chilled vinho verde",
    sensory_detail: "condensation on the glass leaves water rings on the wood barrel tables",
    regular_quote: "crisp and slightly effervescent wine for a warm night",
    regular_name: "Marta",
    regular_since_year: "2019",
    participation_prompt: "What wine fits a coastal evening",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "marisco-fresco-cais-do-sodre",
    spot_name: "Marisco Fresco",
    neighborhood: "Cais do Sodre",
    street: "Rua Nova do Carvalho",
    category: "seafood counter",
    signature_order: "garlic butter clams",
    sensory_detail: "the shells clink loudly against the metal serving bowls",
    regular_quote: "the sauce demands extra bread for dipping",
    regular_name: "Pedro",
    regular_since_year: "2020",
    participation_prompt: "What seafood order do you defend",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "ramblas-tapas-el-raval",
    spot_name: "Ramblas Tapas",
    neighborhood: "El Raval",
    street: "Carrer del Carme",
    category: "tapas bar",
    signature_order: "patatas bravas with aioli",
    sensory_detail: "the spicy tomato sauce is a deep brick red color",
    regular_quote: "potatoes are crispy outside but soft and steaming inside",
    regular_name: "Marc",
    regular_since_year: "2018",
    participation_prompt: "What small plate is mandatory",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "bodega-de-vino-gracia",
    spot_name: "Bodega de Vino",
    neighborhood: "Gracia",
    street: "Carrer de Verdi",
    category: "wine bar",
    signature_order: "vermouth on ice with an olive",
    sensory_detail: "old wine barrels serve as the only tables",
    regular_quote: "they pour the vermouth generous and cold",
    regular_name: "Laura",
    regular_since_year: "2017",
    participation_prompt: "Which aperitif is proper here",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "mariscos-mar-barceloneta",
    spot_name: "Mariscos Mar",
    neighborhood: "Barceloneta",
    street: "Passeig de Joan de Borbo",
    category: "seafood counter",
    signature_order: "fried calamari with lemon",
    sensory_detail: "the batter crackles audibly when you bite into it",
    regular_quote: "fresh squid that is never rubbery",
    regular_name: "Anna",
    regular_since_year: "2016",
    participation_prompt: "What fried dish is the standard",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "bocadillo-bar-eixample",
    spot_name: "Bocadillo Bar",
    neighborhood: "Eixample",
    street: "Carrer de Balmes",
    category: "sandwich counter",
    signature_order: "jamon iberico bocadillo",
    sensory_detail: "they rub the crusty bread with fresh tomato right in front of you",
    regular_quote: "the ham melts on the tongue from its own fat",
    regular_name: "Javier",
    regular_since_year: "2021",
    participation_prompt: "What sandwich brings you back",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "kreuzberg-kebab-kreuzberg",
    spot_name: "Kreuzberg Kebab",
    neighborhood: "Kreuzberg",
    street: "Oranienstrasse",
    category: "kebab shop",
    signature_order: "doner kebab with spicy sauce",
    sensory_detail: "the rotating meat spit hums quietly behind the glass",
    regular_quote: "the red cabbage adds a perfect crunch to the warm bread",
    regular_name: "Ali",
    regular_since_year: "2017",
    participation_prompt: "Which late night order is supreme",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "mitte-brews-mitte",
    spot_name: "Mitte Brews",
    neighborhood: "Mitte",
    street: "Auguststrasse",
    category: "coffee bar",
    signature_order: "oat milk cappuccino",
    sensory_detail: "the ceramic cups have small chips on the bottom rims",
    regular_quote: "the foam art holds its shape until the last sip",
    regular_name: "Felix",
    regular_since_year: "2019",
    participation_prompt: "Where is the finest roast",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "friedrichshain-falafel-friedrichshain",
    spot_name: "Friedrichshain Falafel",
    neighborhood: "Friedrichshain",
    street: "Simon Dach Strasse",
    category: "sandwich counter",
    signature_order: "falafel wrap with tahini",
    sensory_detail: "they crush fresh mint leaves into the wrap",
    regular_quote: "the falafel is green inside from all the fresh herbs",
    regular_name: "Sarah",
    regular_since_year: "2021",
    participation_prompt: "What wrap filling is essential",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "bosphorus-balik-karakoy",
    spot_name: "Bosphorus Balik",
    neighborhood: "Karakoy",
    street: "Kemankes Cd",
    category: "seafood counter",
    signature_order: "balik ekmek with lemon",
    sensory_detail: "the smell of grilled mackerel mixes with the sea salt air",
    regular_quote: "the fish is oily and rich against the crusty bread",
    regular_name: "Emre",
    regular_since_year: "2016",
    participation_prompt: "What street sandwich is local law",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "kadikoy-kebap-kadikoy",
    spot_name: "Kadikoy Kebap",
    neighborhood: "Kadikoy",
    street: "Moda Cd",
    category: "kebab shop",
    signature_order: "iskender kebab with yogurt",
    sensory_detail: "the melted butter sizzles when poured over the meat",
    regular_quote: "the pita underneath soaks up all the rich tomato sauce",
    regular_name: "Zeynep",
    regular_since_year: "2018",
    participation_prompt: "Which meat dish wins out",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "ortakoy-kumpir-ortakoy",
    spot_name: "Ortakoy Kumpir",
    neighborhood: "Ortakoy",
    street: "Mecidiye Koprusu Sk",
    category: "sandwich counter",
    signature_order: "baked potato with olives and sausage",
    sensory_detail: "the steam rises off the huge potatoes lined up in the window",
    regular_quote: "they mash the butter and cheese until it stretches",
    regular_name: "Elif",
    regular_since_year: "2019",
    participation_prompt: "What toppings do you add",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "cihangir-cay-cihangir",
    spot_name: "Cihangir Cay",
    neighborhood: "Cihangir",
    street: "Siraselviler Cd",
    category: "chai stall",
    signature_order: "turkish black tea",
    sensory_detail: "the small glass cups clink against their matching saucers",
    regular_quote: "strong tea that cuts through the afternoon fatigue",
    regular_name: "Burak",
    regular_since_year: "2020",
    participation_prompt: "Which drink keeps you going",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "karama-shawarma-al-karama",
    spot_name: "Karama Shawarma",
    neighborhood: "Al Karama",
    street: "Kuwait St",
    category: "kebab shop",
    signature_order: "chicken shawarma with garlic sauce",
    sensory_detail: "the garlic sauce is bright white and fiercely pungent",
    regular_quote: "they toast the wrap on the grill so it gets crispy",
    regular_name: "Tariq",
    regular_since_year: "2017",
    participation_prompt: "What late night meal do you crave",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "jumeirah-brew-jumeirah",
    spot_name: "Jumeirah Brew",
    neighborhood: "Jumeirah",
    street: "Beach Rd",
    category: "coffee bar",
    signature_order: "iced v60 pour over",
    sensory_detail: "the ice cubes crackle as the hot coffee hits them",
    regular_quote: "a clean bright coffee that helps beat the heat",
    regular_name: "Fatima",
    regular_since_year: "2019",
    participation_prompt: "Where is the favorite iced drink",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "deira-dumplings-deira",
    spot_name: "Deira Dumplings",
    neighborhood: "Deira",
    street: "Al Rigga Rd",
    category: "dumpling counter",
    signature_order: "steamed chicken momos",
    sensory_detail: "the bamboo steamer baskets are stacked six high",
    regular_quote: "the chili chutney brings a serious heat",
    regular_name: "Ananya",
    regular_since_year: "2018",
    participation_prompt: "What dumpling filling works favorite",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "dhiyafah-grill-satwa",
    spot_name: "Dhiyafah Grill",
    neighborhood: "Satwa",
    street: "Al Dhiyafah Rd",
    category: "bistro",
    signature_order: "mixed grill platter",
    sensory_detail: "charcoal smoke drifts out of the kitchen exhaust",
    regular_quote: "the lamb chops are charred perfectly on the edges",
    regular_name: "Khalid",
    regular_since_year: "2016",
    participation_prompt: "What meat platter is unbeatable",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "chowpatty-chaat-girgaon-chowpatty",
    spot_name: "Chowpatty Chaat",
    neighborhood: "Girgaon Chowpatty",
    street: "Marine Dr",
    category: "street food stall",
    signature_order: "bhelpuri with tangy chutney",
    sensory_detail: "the puffed rice crackles when the tamarind sauce hits it",
    regular_quote: "the balance of sweet and spicy is exactly right",
    regular_name: "Rahul",
    regular_since_year: "2016",
    participation_prompt: "Which street snack is your go to",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "andheri-vada-pav-andheri-west",
    spot_name: "Andheri Vada Pav",
    neighborhood: "Andheri West",
    street: "Lokhandwala",
    category: "sandwich counter",
    signature_order: "hot vada pav with dry garlic chutney",
    sensory_detail: "the green chilies are fried until they blister",
    regular_quote: "the bun is soft but the potato patty stays crispy",
    regular_name: "Sneha",
    regular_since_year: "2018",
    participation_prompt: "What bread snack is standard",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "colaba-chai-colaba",
    spot_name: "Colaba Chai",
    neighborhood: "Colaba",
    street: "Causeway",
    category: "chai stall",
    signature_order: "cutting chai with ginger",
    sensory_detail: "the intense smell of boiled cardamom and milk fills the air",
    regular_quote: "strong enough to wake you up immediately",
    regular_name: "Pooja",
    regular_since_year: "2019",
    participation_prompt: "What tea order is mandatory",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "fort-frankie-fort",
    spot_name: "Fort Frankie",
    neighborhood: "Fort",
    street: "DN Road",
    category: "kebab shop",
    signature_order: "mutton frankie",
    sensory_detail: "the egg coating on the roti sizzles on the hot tawa",
    regular_quote: "the pickled onions add a sharp crunch to every bite",
    regular_name: "Karan",
    regular_since_year: "2020",
    participation_prompt: "Which roll filling is favorite",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "chandni-chole-old-delhi",
    spot_name: "Chandni Chole",
    neighborhood: "Old Delhi",
    street: "Chandni Chowk",
    category: "curry house",
    signature_order: "chole bhature",
    sensory_detail: "the giant wok of hot oil bubbles continuously",
    regular_quote: "the fried bread is fluffy and the chickpeas are heavily spiced",
    regular_name: "Rohan",
    regular_since_year: "2016",
    participation_prompt: "Which heavy meal is worth it",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "majnu-momos-majnu-ka-tila",
    spot_name: "Majnu Momos",
    neighborhood: "Majnu Ka Tila",
    street: "Outer Ring Rd",
    category: "dumpling counter",
    signature_order: "steamed pork momos with red chili sauce",
    sensory_detail: "the red chili sauce leaves a fiery stain on the paper plate",
    regular_quote: "the filling is juicy and the dough is rolled thin",
    regular_name: "Tenzin",
    regular_since_year: "2018",
    participation_prompt: "What dumpling sauce ratio is ideal",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "cpcoffee-house-connaught-place",
    spot_name: "CPCoffee House",
    neighborhood: "Connaught Place",
    street: "Inner Circle",
    category: "coffee bar",
    signature_order: "cold coffee with ice cream",
    sensory_detail: "the tall glass is frosted from the cold milk",
    regular_quote: "a thick sweet coffee that acts as a dessert",
    regular_name: "Riya",
    regular_since_year: "2019",
    participation_prompt: "Where is the favorite cold brew",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "lajpat-chaat-lajpat-nagar",
    spot_name: "Lajpat Chaat",
    neighborhood: "Lajpat Nagar",
    street: "Central Market",
    category: "street food stall",
    signature_order: "dahi bhalla",
    sensory_detail: "the yogurt is thick and dusted with roasted cumin powder",
    regular_quote: "cooling yogurt balances the sharp tamarind chutney",
    regular_name: "Manish",
    regular_since_year: "2020",
    participation_prompt: "What chaat dish is your standard",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "yaowarat-noodles-chinatown",
    spot_name: "Yaowarat Noodles",
    neighborhood: "Chinatown",
    street: "Yaowarat Rd",
    category: "noodle shop",
    signature_order: "duck noodle soup",
    sensory_detail: "the dark soy broth leaves a rich brown ring on the bowl",
    regular_quote: "the duck meat falls right off the bone",
    regular_name: "Somchai",
    regular_since_year: "2017",
    participation_prompt: "What soup broth cures everything",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "sukhumvit-som-tum-sukhumvit",
    spot_name: "Sukhumvit Som Tum",
    neighborhood: "Sukhumvit",
    street: "Soi 11",
    category: "street food stall",
    signature_order: "spicy papaya salad with crab",
    sensory_detail: "the wooden pestle thuds loudly against the clay mortar",
    regular_quote: "the lime and chili dressing is perfectly sharp",
    regular_name: "Niran",
    regular_since_year: "2018",
    participation_prompt: "Which salad spice level do you order",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "thong-lo-coffee-thong-lo",
    spot_name: "Thong Lo Coffee",
    neighborhood: "Thong Lo",
    street: "Soi 55",
    category: "coffee bar",
    signature_order: "iced thai milk tea",
    sensory_detail: "the bright orange tea stains the crushed ice",
    regular_quote: "sweet and creamy without losing the tea flavor",
    regular_name: "Kanya",
    regular_since_year: "2019",
    participation_prompt: "Where is the favorite iced tea hiding",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "ari-bakery-ari",
    spot_name: "Ari Bakery",
    neighborhood: "Ari",
    street: "Soi Ari 1",
    category: "bakery cafe",
    signature_order: "pandan custard bread",
    sensory_detail: "the green custard oozes out of the soft white bun",
    regular_quote: "the pandan flavor is floral and earthy",
    regular_name: "Piti",
    regular_since_year: "2020",
    participation_prompt: "Which sweet bread is your go to",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "shibuya-ramen-shibuya",
    spot_name: "Shibuya Ramen",
    neighborhood: "Shibuya",
    street: "Center Gai",
    category: "ramen bar",
    signature_order: "rich tonkotsu ramen",
    sensory_detail: "the steam from the boiling noodle water fogs the mirrors",
    regular_quote: "broth so rich it coats the back of the spoon",
    regular_name: "Kenji",
    regular_since_year: "2016",
    participation_prompt: "Which noodle texture is favorite",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "shinjuku-yakitori-shinjuku",
    spot_name: "Shinjuku Yakitori",
    neighborhood: "Shinjuku",
    street: "Omoide Yokocho",
    category: "izakaya",
    signature_order: "chicken thigh and scallion skewers",
    sensory_detail: "the smoke from the binchotan charcoal is thick and sweet",
    regular_quote: "the tare sauce is dark and deeply savory",
    regular_name: "Yumi",
    regular_since_year: "2017",
    participation_prompt: "What skewer defines this alley",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "harajuku-crepes-harajuku",
    spot_name: "Harajuku Crepes",
    neighborhood: "Harajuku",
    street: "Takeshita St",
    category: "dessert shop",
    signature_order: "strawberry matcha crepe",
    sensory_detail: "the paper cone is warm from the fresh crepe batter",
    regular_quote: "the cream is light and the strawberries are tart",
    regular_name: "Sakura",
    regular_since_year: "2019",
    participation_prompt: "Which sweet wrap is your favorite",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "roppongi-katsu-roppongi",
    spot_name: "Roppongi Katsu",
    neighborhood: "Roppongi",
    street: "Roppongi Dori",
    category: "bistro",
    signature_order: "pork katsu curry",
    sensory_detail: "the panko breading crunches loudly with every bite",
    regular_quote: "a thick mild curry that warms you right up",
    regular_name: "Taro",
    regular_since_year: "2020",
    participation_prompt: "What fried dish belongs here",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "myeongdong-kalguksu-myeongdong",
    spot_name: "Myeongdong Kalguksu",
    neighborhood: "Myeongdong",
    street: "Myeongdong 10-gil",
    category: "noodle shop",
    signature_order: "handmade knife cut noodles",
    sensory_detail: "the flour dust covers the wooden cutting board",
    regular_quote: "the broth is garlicky and the kimchi is perfectly spicy",
    regular_name: "Minho",
    regular_since_year: "2017",
    participation_prompt: "What noodle bowl is a must",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "hongdae-tteok-hongdae",
    spot_name: "Hongdae Tteok",
    neighborhood: "Hongdae",
    street: "Eoulmadang-ro",
    category: "street food stall",
    signature_order: "spicy tteokbokki with fish cake",
    sensory_detail: "the red gochujang sauce bubbles thickly in a wide metal pan",
    regular_quote: "the rice cakes are incredibly chewy and soak up the heat",
    regular_name: "Jiyeon",
    regular_since_year: "2018",
    participation_prompt: "Which street snack is the standard",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "gangnam-cafe-gangnam",
    spot_name: "Gangnam Cafe",
    neighborhood: "Gangnam",
    street: "Teheran-ro",
    category: "bakery cafe",
    signature_order: "garlic cream cheese bread",
    sensory_detail: "the shiny glaze on the bread is sticky to the touch",
    regular_quote: "a wild combination of sweet cream and savory garlic",
    regular_name: "Sujin",
    regular_since_year: "2019",
    participation_prompt: "Which bread trend is actually good",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "jongno-bingsu-jongno",
    spot_name: "Jongno Bingsu",
    neighborhood: "Jongno",
    street: "Insadong-gil",
    category: "dessert shop",
    signature_order: "injeolmi shaved ice",
    sensory_detail: "the roasted soybean powder flies everywhere if you exhale",
    regular_quote: "the ice is shaved so fine it feels like cold dust",
    regular_name: "Donghae",
    regular_since_year: "2020",
    participation_prompt: "What cold dessert is unbeatable",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "lau-pa-sat-satay-downtown-core",
    spot_name: "Lau Pa Sat Satay",
    neighborhood: "Downtown Core",
    street: "Raffles Quay",
    category: "kebab shop",
    signature_order: "beef and mutton satay",
    sensory_detail: "the smoke from the grills covers the entire street",
    regular_quote: "the peanut sauce is chunky and sweet",
    regular_name: "Raj",
    regular_since_year: "2017",
    participation_prompt: "What skewer meat is the favorite choice",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "tiong-bahru-bakery-tiong-bahru",
    spot_name: "Tiong Bahru Bakery",
    neighborhood: "Tiong Bahru",
    street: "Eng Hoon St",
    category: "bakery cafe",
    signature_order: "almond croissant",
    sensory_detail: "the flaked almonds on top are toasted dark brown",
    regular_quote: "massive buttery layers that leave a mess on the plate",
    regular_name: "Jun",
    regular_since_year: "2019",
    participation_prompt: "What pastry pairs favorite with morning coffee",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "newton-seafood-newton",
    spot_name: "Newton Seafood",
    neighborhood: "Newton",
    street: "Clemenceau Ave",
    category: "seafood counter",
    signature_order: "chili crab with fried mantou",
    sensory_detail: "the thick red chili sauce coats the crab shells completely",
    regular_quote: "the fried buns are mandatory to soak up the sauce",
    regular_name: "Kumar",
    regular_since_year: "2020",
    participation_prompt: "Which crab preparation wins here",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "surry-hills-brew-surry-hills",
    spot_name: "Surry Hills Brew",
    neighborhood: "Surry Hills",
    street: "Crown St",
    category: "coffee bar",
    signature_order: "flat white",
    sensory_detail: "the espresso machine shines under the warm yellow lights",
    regular_quote: "the milk is steamed to a perfect glossy texture",
    regular_name: "Liam",
    regular_since_year: "2018",
    participation_prompt: "Where is the favorite morning roast",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "bondi-brunch-bondi",
    spot_name: "Bondi Brunch",
    neighborhood: "Bondi",
    street: "Campbell Pde",
    category: "brunch counter",
    signature_order: "smashed avocado on sourdough",
    sensory_detail: "the sourdough crust requires serious effort to cut through",
    regular_quote: "the feta cheese and chili flakes balance the rich avocado",
    regular_name: "Chloe",
    regular_since_year: "2019",
    participation_prompt: "What avocado toast is widely defended",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "darlinghurst-wine-darlinghurst",
    spot_name: "Darlinghurst Wine",
    neighborhood: "Darlinghurst",
    street: "Victoria St",
    category: "wine bar",
    signature_order: "chilled natural pet nat",
    sensory_detail: "the wine bubbles actively in the glass for several minutes",
    regular_quote: "funky and fresh wine that drinks like cider",
    regular_name: "Olivia",
    regular_since_year: "2021",
    participation_prompt: "What wine pour do you defend",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "haymarket-dumpling-haymarket",
    spot_name: "Haymarket Dumpling",
    neighborhood: "Haymarket",
    street: "Dixon St",
    category: "dumpling counter",
    signature_order: "pan fried soup dumplings",
    sensory_detail: "the crispy bottom of the dumpling cracks loudly",
    regular_quote: "wait a minute before eating or the soup will burn you",
    regular_name: "Ethan",
    regular_since_year: "2017",
    participation_prompt: "Which dumpling is worth burning your mouth for",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "fitzroy-coffee-fitzroy",
    spot_name: "Fitzroy Coffee",
    neighborhood: "Fitzroy",
    street: "Brunswick St",
    category: "coffee bar",
    signature_order: "batch brew filter coffee",
    sensory_detail: "the glass carafe is slightly stained from dark roasts",
    regular_quote: "clean bright coffee that tastes like berries",
    regular_name: "Noah",
    regular_since_year: "2018",
    participation_prompt: "What filter coffee is the favorite",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "carlton-pizza-carlton",
    spot_name: "Carlton Pizza",
    neighborhood: "Carlton",
    street: "Lygon St",
    category: "slice shop",
    signature_order: "margherita slice",
    sensory_detail: "the mozzarella pools slightly in the middle of the slice",
    regular_quote: "the dough ferments long enough to taste slightly sour",
    regular_name: "Mia",
    regular_since_year: "2019",
    participation_prompt: "Which slice is true to tradition",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "richmond-pho-richmond",
    spot_name: "Richmond Pho",
    neighborhood: "Richmond",
    street: "Victoria St",
    category: "pho shop",
    signature_order: "chicken pho with lime",
    sensory_detail: "the steam carries the scent of star anise to the street",
    regular_quote: "lighter broth but packed with umami",
    regular_name: "Ava",
    regular_since_year: "2021",
    participation_prompt: "Which pho place is the local favorite",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "south-yarra-sweets-south-yarra",
    spot_name: "South Yarra Sweets",
    neighborhood: "South Yarra",
    street: "Chapel St",
    category: "gelato shop",
    signature_order: "pistachio gelato",
    sensory_detail: "the gelato is a pale natural green not bright artificial",
    regular_quote: "dense and creamy with roasted nut chunks",
    regular_name: "Thomas",
    regular_since_year: "2017",
    participation_prompt: "What gelato flavor do you order",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "surulere-suya-surulere",
    spot_name: "Surulere Suya",
    neighborhood: "Surulere",
    street: "Adeniran Ogunsanya",
    category: "kebab shop",
    signature_order: "beef suya with extra onions",
    sensory_detail: "the glowing charcoal illuminates the street corner",
    regular_quote: "the yaji spice mix has the perfect peanut and chili ratio",
    regular_name: "Chidi",
    regular_since_year: "2018",
    participation_prompt: "Which street grill is widely defended",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "balogun-snacks-lagos-island",
    spot_name: "Balogun Snacks",
    neighborhood: "Lagos Island",
    street: "Broad St",
    category: "bakery",
    signature_order: "hot puff puff",
    sensory_detail: "the deep fryer bubbles loudly over the market noise",
    regular_quote: "soft dough balls that are sweet and perfectly greasy",
    regular_name: "Ngozi",
    regular_since_year: "2019",
    participation_prompt: "What fried snack is your go to",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "victoria-island-grill-victoria-island",
    spot_name: "Victoria Island Grill",
    neighborhood: "Victoria Island",
    street: "Adeola Odeku",
    category: "bistro",
    signature_order: "nkwobi",
    sensory_detail: "the wooden bowl it is served in is stained from palm oil",
    regular_quote: "spicy cow foot that is rich and incredibly gelatinous",
    regular_name: "Femi",
    regular_since_year: "2017",
    participation_prompt: "What spicy dish belongs on the map",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "ikoyi-fish-ikoyi",
    spot_name: "Ikoyi Fish",
    neighborhood: "Ikoyi",
    street: "Awolowo Rd",
    category: "seafood counter",
    signature_order: "grilled catfish",
    sensory_detail: "the skin of the fish is charred black and crispy",
    regular_quote: "the pepper soup spice kicks in after the second bite",
    regular_name: "Aisha",
    regular_since_year: "2021",
    participation_prompt: "Which seafood grill belongs on the map",
    cta_door: "app_download_supporter",
    source_status: "operator_seed_for_review",
  },
  {
    id: "bo-kaap-bites-bo-kaap",
    spot_name: "Bo Kaap Bites",
    neighborhood: "Bo-Kaap",
    street: "Wale St",
    category: "bakery",
    signature_order: "sweet koeksisters",
    sensory_detail: "the syrup drips off the braided dough onto the wax paper",
    regular_quote: "spiced perfectly with cinnamon and soaked in syrup",
    regular_name: "Fatima",
    regular_since_year: "2018",
    participation_prompt: "What sweet pastry is essential here",
    cta_door: "local_guide",
    source_status: "community_submitted_draft",
  },
  {
    id: "kloof-street-coffee-gardens",
    spot_name: "Kloof Street Coffee",
    neighborhood: "Gardens",
    street: "Kloof St",
    category: "coffee bar",
    signature_order: "flat white",
    sensory_detail: "the coffee grounds smell earthy and strong at the counter",
    regular_quote: "the milk is silky and never burnt",
    regular_name: "Pieter",
    regular_since_year: "2019",
    participation_prompt: "Where is the favorite coffee hideout",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "bree-street-wine-city-bowl",
    spot_name: "Bree Street Wine",
    neighborhood: "City Bowl",
    street: "Bree St",
    category: "wine bar",
    signature_order: "local chenin blanc",
    sensory_detail: "the glasses clink constantly in the small crowded room",
    regular_quote: "crisp wine that pairs with the warm evening",
    regular_name: "Sophie",
    regular_since_year: "2017",
    participation_prompt: "What wine glass starts the night",
    cta_door: "app_download_supporter",
    source_status: "community_submitted_draft",
  },
  {
    id: "sea-point-catch-sea-point",
    spot_name: "Sea Point Catch",
    neighborhood: "Sea Point",
    street: "Main Rd",
    category: "seafood counter",
    signature_order: "fried hake and chips",
    sensory_detail: "the vinegar smell hits you immediately",
    regular_quote: "the fish batter is light and golden brown",
    regular_name: "Johan",
    regular_since_year: "2021",
    participation_prompt: "What fried fish is worth the wait",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
] satisfies RallioLocalSignal[];
