import type { RallioLocalSignal } from "@/lib/content/types";

// Generated from rallio_taste_map_dataset.csv. Only approved, non-placeholder rows are included.
export const rallioTorontoSourceSignals = [
  {
    id: "north-window-slice-ossington",
    spot_name: "North Window Slice",
    neighborhood: "Ossington",
    street: "Ossington Ave",
    category: "slice shop",
    signature_order: "pepperoni slice with hot honey and a side cup of ranch",
    sensory_detail:
      "The crust stays crackly right to the tip, and the front window picks up a warm fog every time a fresh tray lands.",
    regular_quote: "If the corner slice looks newer than the rest, that's mine.",
    regular_name: "Maya",
    regular_since_year: "2019",
    participation_prompt: "What order would you defend here?",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "soft-pour-coffee-ossington",
    spot_name: "Soft Pour Coffee",
    neighborhood: "Ossington",
    street: "Foxley St",
    category: "coffee bar",
    signature_order: "short oat cortado and the salted butter cookie",
    sensory_detail:
      "There is always that first grinder burst around 8:15, and the citrus from the espresso hangs near the door.",
    regular_quote: "Their cortado tastes like they actually calibrated the thing.",
    regular_name: "Jules",
    regular_since_year: "2022",
    participation_prompt: "What makes a coffee bar worth repeating on your block?",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "low-glass-wine-ossington",
    spot_name: "Low Glass Wine",
    neighborhood: "Ossington",
    street: "Dundas St W",
    category: "wine bar",
    signature_order: "chilled gamay and anchovy toast",
    sensory_detail:
      "The room stays dim until sunset, then the bottles in the back start catching amber light.",
    regular_quote: "My sit-at-the-bar and reset place.",
    regular_name: "Priya",
    regular_since_year: "2020",
    participation_prompt: "Which pour would keep you coming back here?",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "morning-counter-ossington",
    spot_name: "Morning Counter",
    neighborhood: "Ossington",
    street: "Queen St W",
    category: "brunch counter",
    signature_order: "soft scrambled eggs, hash browns, and marmalade on rye",
    sensory_detail:
      "The flat-top keeps throwing off buttery steam, and the hash browns hit the pass louder than the plates.",
    regular_quote: "You go early or you wait, and honestly both outcomes make sense.",
    regular_name: "Daniel",
    regular_since_year: "2017",
    participation_prompt: "What is the no-regrets brunch order at a place like this?",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "two-napkins-ossington",
    spot_name: "Two Napkins",
    neighborhood: "Ossington",
    street: "Ossington Ave",
    category: "sandwich counter",
    signature_order: "mortadella sandwich with pistachio spread and chili crunch chips",
    sensory_detail:
      "The bread gives off that floury sweetness when they split it, and the wrapping paper always comes out warm.",
    regular_quote: "If it doesn't drip a little, they built it wrong.",
    regular_name: "Elena",
    regular_since_year: "2024",
    participation_prompt: "Which sandwich detail decides the whole lunch for you?",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
  {
    id: "cream-bell-ossington",
    spot_name: "Cream Bell",
    neighborhood: "Ossington",
    street: "Queen St W",
    category: "dessert shop",
    signature_order: "miso caramel soft serve in a cup with extra crumble",
    sensory_detail:
      "The machine hum is constant, and the caramel smell sticks near the counter even when the door opens.",
    regular_quote:
      "Cup over cone. I am not playing games with a melting dessert on Ossington.",
    regular_name: "Owen",
    regular_since_year: "2016",
    participation_prompt: "Do you go cone or cup at a dessert stop like this?",
    cta_door: "local_guide",
    source_status: "operator_seed_for_review",
  },
] satisfies RallioLocalSignal[];
